### ISSUE TITLE
Bootstrap version

### ISSUE THREAD

**Issue by papyr** [mcintyre321/FormFactory#12]
_Once again another great genius component!_

This is more a request and not a bug, would be great if we could configure the form helper to also pick up a version of bootstrap BS 3.3 or BS 4.x during its form building process.

**Comment by mcintyre321** [comment]
It would be nice if FF was design-framework non-specific to be honest. I think there might need to be a step which transforms the templates before they are compiled/rendered (although you could do this afterwards).

I've considered making the html FF outputs very simple, and then feeding it into a CsQuery DOM, which could then be transformed to have the correct markup for a particular framework.

**Comment by papyr** [comment]
couple of suggestions for anyone else looking.
After looking around the twitterbootstrap mvc dll link (http://bit.ly/1Ln3OCW) might be a good option,
but it seems like its no longer open source/free. I also saw your suggestion on the CsQuery port will give it a try

**Comment by mcintyre321** [comment]
Another option would be to transform the output, rather than changing the tables. 

If all the bootstrap based markup was removed from the templates, we could add a parameter to the Render helper which passes a transformer, which is a 

````
interface Transformer{
    public string TransformOutput(PropertyVm propertyVm, string defaultRenderedOutput)
}
````

`Html.PropertiesFor(someObject).Render(Html, new Bootstrap3Transformer());
