### ISSUE TITLE
Update to 4.6.1 

### ISSUE THREAD

**Issue by patagoniahiker** [mcintyre321/FormFactory#18]
Hi, can you please update to current 4.6.1 should be straight forward.
thanks

**Comment by skorunka** [comment]
Package FormFactory.AspNetCore 2.0.112 is not compatible with net462, why?

**Comment by mcintyre321** [comment]
The 4.5.1 version is for MVC5, the AspNetCore one is packaged for .NETStandard 1.6

Maybe there's a change to project.json you could suggest that would enable it?

**Comment by skorunka** [comment]
"The 4.5.1 version is for MVC5" that's not actually true. It is just a .NET 4.5.1 Framework. Unless your project is using a features the 451 does not have, why not to target this FW and allow other project to use your library without forcing them to upgrade to 461, 461 etc.?
 
For example, I'm working on Asp.NET Core MVC project and because FormFactory.AspNetCore targets "netstandard1.6" only I can not reference it in my project, as I target net462.

I believe, the only change you have to do is in "FormFactory.AspNetCore" project, file "project.json":
```
  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    },
   **"net451": {}**
  }
```

**Comment by mcintyre321** [comment]
Please, send a PR to this effect and I will merge it!

**Comment by mcintyre321** [comment]
FF is now 451 and .NETCoreApp 1.1 compatible
